# Generated by Django 5.1 on 2024-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("send_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("sent", "Sent")], max_length=50
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        help_text="Enter comma-separated list of email addresses"
                    ),
                ),
            ],
        ),
    ]
